### ISSUE TITLE
fix: CORS setting 

### ISSUE THREAD

**Issue by JunhyeongPark-kr** [sunnybraille/sunnybraille-server#141]
https://velog.io/@rhqjatn2398/Access-Control-Expose-Headers-CORS-safelisted-response-header

개발자도구에는 headers 항목이 잘 나오는데, 사이트에서는 access가 안되어 확인해보니 제3자가 만든 headers는 추가적인 설정을 해야한다...는 내용이 있는데, 한번 보시고 알려주세요!

@gitchannn

**Comment by gitchannn** [comment]
@JunhyeongPark-kr 이부분 해결된건가요??!!
더이상 유효한 이슈 아니면 close 부탁드립니당!

**Comment by JunhyeongPark-kr** [comment]
headers 없이 쿠키로만 구현해서 close 하겠습니다
