### ISSUE TITLE
feat: kauth logout api 

### ISSUE THREAD

**Issue by JunhyeongPark-kr** [sunnybraille/sunnybraille-server#158]
<img width="818" alt="image" src="https://github.com/sunnybraille/sunnybraille-server/assets/115399447/384bb4ff-7482-4b9c-a5e8-0aac55da4775">

id/pw를 이용한 로그아웃의 경우에는, 따로 api에 요청을 보내서 서버와 클라이언트 모두에서 로그아웃 상태를 만들고 있습니다.

https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#logout

카카오 로그아웃 관리도 서버에 상태를 전달하는 다리가 하나 필요해보입니다.

@gitchannn

**Comment by gitchannn** [comment]
기존의 `/logout` API를 그대로 사용하면 되기 때문에 해당 api는 불필요할 것 같아서 close하겠습니다!
